shellEmulator: true

trustPolicy: no-downgrade

packages:
  - "packages/*"
  - "examples/*"

patchedDependencies:
  "@total-typescript/ts-reset": patches/@total-typescript__ts-reset.patch

onlyBuiltDependencies:
  - esbuild
  - lefthook
